### ISSUE TITLE
Labels are not set in a timely manner

### ISSUE THREAD

**Issue by mzeinstra** [ProfessionalWiki/AutomatedValues#29]
We experience labels sometimes take over an hour to be set in Wiki. Which hook is used to execute the change.

In our use case we make a change that triggers the change for two out of the three languages for our labels. The last label (so far always english) takes a long time to be set by the exertions.

Is there anything that we can check why this takes a while?

**Comment by mzeinstra** [comment]
Interestingly it seems that is not update in the language of the interface. When I switch to the French as the interface language the english label appears. When I switch back to english it disappears..

**Comment by JeroenDeDauw** [comment]
Automated Values sets the labels immediately as part of the revision created by the edit. So there is definitely no delay in the part that Automated Values plays.

(Hook: https://github.com/ProfessionalWiki/AutomatedValues/blob/master/src/Hooks.php#L18-L36)

What you are seeing is presumably something that will always happen for label updates on your wiki, regardless if they come from Automated Values or not. My guess is that the "term indexing" is taking some time because it has some "deferred" jobs. You might be able to fix that by running runJobs.php or some other maintenance script more often. A general Wikibase question that could go onto the Telegram.

**Comment by mzeinstra** [comment]
Thank you, make sense. Good to have this documented (in this ticket) if others experience the same.
